Repository GodotVR/godot_openxr_vendors, pull requests merged in 2024-05, with the labels that each got.

#125 Hand Silhouette Outline shader/material for Meta Hand-tracking Model
  demo/assets/hand_outline.gdshader
  demo/assets/hand_silhouette.gdshader
  demo/assets/hand_silhouette_outline_mat.tres
  demo/main.tscn
Labels: enhancement

#137 Implement XR_FB_composition_layer_alpha_blend extension wrapper
  common/src/main/cpp/extensions/openxr_fb_composition_layer_alpha_blend_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_fb_composition_layer_alpha_blend_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
Labels: enhancement

#136 Implement XR_FB_composition_layer_settings extension wrapper
  common/src/main/cpp/extensions/openxr_fb_composition_layer_settings_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_fb_composition_layer_settings_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
Labels: enhancement

#138 Implement the structure for adding API and hand-written documentation
  .github/workflows/documentation.yml
  common/src/main/cpp/classes/openxr_fb_spatial_entity.cpp
  common/src/main/cpp/classes/openxr_meta_passthrough_color_lut.cpp
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_capsules_extension_wrapper.cpp
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  doc_classes/KhronosEditorExportPlugin.xml
  doc_classes/KhronosEditorPlugin.xml
  doc_classes/LynxEditorPlugin.xml
  doc_classes/MetaEditorExportPlugin.xml
  doc_classes/MetaEditorPlugin.xml
  doc_classes/OpenXREditorExportPlugin.xml
  doc_classes/OpenXRFbBodyTrackingExtensionWrapper.xml
  doc_classes/OpenXRFbCompositionLayerSecureContentExtensionWrapper.xml
  doc_classes/OpenXRFbFaceTrackingExtensionWrapper.xml
  doc_classes/OpenXRFbHandTrackingAimExtensionWrapper.xml
  doc_classes/OpenXRFbHandTrackingCapsulesExtensionWrapper.xml
  doc_classes/OpenXRFbHandTrackingMesh.xml
  doc_classes/OpenXRFbHandTrackingMeshExtensionWrapper.xml
  doc_classes/OpenXRFbPassthroughExtensionWrapper.xml
  doc_classes/OpenXRFbPassthroughGeometry.xml
  doc_classes/OpenXRFbRenderModel.xml
  doc_classes/OpenXRFbRenderModelExtensionWrapper.xml
  doc_classes/OpenXRFbSceneCaptureExtensionWrapper.xml
  doc_classes/OpenXRFbSceneExtensionWrapper.xml
  doc_classes/OpenXRFbSceneManager.xml
  doc_classes/OpenXRFbSpatialEntity.xml
  doc_classes/OpenXRFbSpatialEntityContainerExtensionWrapper.xml
  doc_classes/OpenXRFbSpatialEntityExtensionWrapper.xml
  doc_classes/OpenXRFbSpatialEntityQuery.xml
  doc_classes/OpenXRFbSpatialEntityQueryExtensionWrapper.xml
  doc_classes/OpenXRFbSpatialEntityStorageExtensionWrapper.xml
  doc_classes/OpenXRHtcFacialTrackingExtensionWrapper.xml
  doc_classes/OpenXRMetaPassthroughColorLut.xml
  doc_classes/OpenXRMetaSpatialEntityMeshExtensionWrapper.xml
  doc_classes/PicoEditorPlugin.xml
  docs/.gitignore
  docs/.python-version
  docs/Makefile
  docs/README.md
  docs/_extensions/gdscript.py
  docs/_static/css/custom.css
  docs/_templates/breadcrumbs.html
  docs/conf.py
  docs/img/logo.png
  docs/index.rst
  docs/make.bat
  docs/make_rst.py
  docs/requirements.txt
  scripts/update_doc_classes_xml.sh
Labels: enhancement

#121 Add support for developer-created spatial anchors via XR_FB_spatial_entity
  CHANGES.md
  common/src/main/cpp/classes/openxr_fb_spatial_anchor_manager.cpp
  common/src/main/cpp/classes/openxr_fb_spatial_entity.cpp
  common/src/main/cpp/extensions/openxr_fb_spatial_entity_extension_wrapper.cpp
  common/src/main/cpp/extensions/openxr_fb_spatial_entity_storage_extension_wrapper.cpp
  common/src/main/cpp/include/classes/openxr_fb_spatial_anchor_manager.h
  common/src/main/cpp/include/classes/openxr_fb_spatial_entity.h
  common/src/main/cpp/include/extensions/openxr_fb_spatial_entity_extension_wrapper.h
  common/src/main/cpp/include/extensions/openxr_fb_spatial_entity_storage_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
  demo/assets/cross-grid-material.tres
  demo/assets/wireframe-material.tres
  demo/main.gd
  demo/main.tscn
  demo/project.godot
  demo/scene_anchor.tscn
  demo/scene_global_mesh.tscn
  demo/spatial_anchor.gd
  demo/spatial_anchor.tscn
Labels: enhancement

#128 Add support for sharing and bulk saving (and sharing) of spatial anchors
  common/src/main/cpp/classes/openxr_fb_spatial_entity.cpp
  common/src/main/cpp/classes/openxr_fb_spatial_entity_batch.cpp
  common/src/main/cpp/classes/openxr_fb_spatial_entity_user.cpp
  common/src/main/cpp/extensions/openxr_fb_spatial_entity_sharing_extension_wrapper.cpp
  common/src/main/cpp/extensions/openxr_fb_spatial_entity_storage_batch_extension_wrapper.cpp
  common/src/main/cpp/extensions/openxr_fb_spatial_entity_user_extension_wrapper.cpp
  common/src/main/cpp/include/classes/openxr_fb_spatial_entity.h
  common/src/main/cpp/include/classes/openxr_fb_spatial_entity_batch.h
  common/src/main/cpp/include/classes/openxr_fb_spatial_entity_user.h
  common/src/main/cpp/include/extensions/openxr_fb_spatial_entity_sharing_extension_wrapper.h
  common/src/main/cpp/include/extensions/openxr_fb_spatial_entity_storage_batch_extension_wrapper.h
  common/src/main/cpp/include/extensions/openxr_fb_spatial_entity_user_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
  demo/spatial_anchor.gd
Labels: enhancement

#139 Implement hole punch functionality for `OpenXRFbPassthroughGeometry` node
  common/src/main/cpp/classes/openxr_fb_passthrough_geometry.cpp
  common/src/main/cpp/include/classes/openxr_fb_passthrough_geometry.h
  demo/main.gd
Labels: enhancement

#143 Remove miscellaneous things that were inadvertedly copied into docs
  docs/README.md
  docs/make_rst.py
Labels: bug, documentation

#145 Update property usage for hand tracking mesh scale override properites
  common/src/main/cpp/classes/openxr_fb_hand_tracking_mesh.cpp
Labels: enhancement

#147 Update hand mesh data fetch process
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_mesh_extension_wrapper.cpp
Labels: bug

#142 Implement XR_META_automatic_layer_filter extension
  common/src/main/cpp/extensions/openxr_fb_composition_layer_settings_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_fb_composition_layer_settings_extension_wrapper.h
Labels: enhancement

#148 Add settings for HTC
  CHANGES.md
  common/src/main/cpp/export/khronos_export_plugin.cpp
  common/src/main/cpp/include/export/khronos_export_plugin.h
  godotopenxrkhronos/src/main/java/org/godotengine/openxr/vendors/khronos/GodotOpenXRKhronos.kt
Labels: enhancement

#154 Generate normals and tangets for Meta's global scene mesh
  common/src/main/cpp/classes/openxr_fb_spatial_entity.cpp
Labels: enhancement

#159 Fix docs error about unresolved "Gradient" class
  docs/make_rst.py
Labels: documentation

#160 Always build docs on GitHub Actions; only deploy on `master`
  .github/workflows/documentation.yml
Labels: documentation

#155 Create fb passthrough sample project
  build.gradle
  demo/assets/color-lut-inverted-32.png.import
  demo/assets/color-lut.png.import
  demo/main.gd
  demo/main.tscn
  samples/.gitattributes
  samples/.gitignore
  samples/fb-passthrough-sample/color-lut-inverted-32.png
  samples/fb-passthrough-sample/color-lut-inverted-32.png.import
  samples/fb-passthrough-sample/color-lut-orange-64.png
  samples/fb-passthrough-sample/color-lut-orange-64.png.import
  samples/fb-passthrough-sample/export_presets.cfg
  samples/fb-passthrough-sample/geometry.gd
  samples/fb-passthrough-sample/icon.svg
  samples/fb-passthrough-sample/icon.svg.import
  samples/fb-passthrough-sample/main.gd
  samples/fb-passthrough-sample/main.tscn
  samples/fb-passthrough-sample/openxr_action_map.tres
  samples/fb-passthrough-sample/project.godot
  samples/fb-passthrough-sample/raycast.gd
  samples/fb-passthrough-sample/slider.gd
  samples/fb-passthrough-sample/slider.tscn
Labels: documentation, enhancement

#158 Apply reference frame transform to `OpenXRFbPassthroughGeometry`
  common/src/main/cpp/classes/openxr_fb_passthrough_geometry.cpp
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  common/src/main/cpp/include/classes/openxr_fb_passthrough_geometry.h
Labels: bug

#161 Add fb composition layer sample project
  samples/fb-composition-layers-sample/example_panel.gd
  samples/fb-composition-layers-sample/example_panel.tscn
  samples/fb-composition-layers-sample/export_presets.cfg
  samples/fb-composition-layers-sample/icon.svg
  samples/fb-composition-layers-sample/icon.svg.import
  samples/fb-composition-layers-sample/main.gd
  samples/fb-composition-layers-sample/main.tscn
  samples/fb-composition-layers-sample/openxr_action_map.tres
  samples/fb-composition-layers-sample/project.godot
  samples/fb-composition-layers-sample/raycast.gd
Labels: documentation, enhancement

#151 Add support for HTC passthrough
  CHANGES.md
  CONTRIBUTORS.md
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  common/src/main/cpp/extensions/openxr_htc_passthrough_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_htc_passthrough_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
Labels: enhancement
