Repository GodotVR/godot_openxr_vendors, pull requests merged in 2024-10, with the labels that each got.

#215 Add gradle tasks related to zipping sample projects
  .gitignore
  build.gradle
Labels: enhancement

#221 Fix `OpenXRFbPassthroughExtensionWrapper` from wiping out the next pointer chain for system properties
  plugin/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
Labels: bug

#216 Add two modes of pico hand tracking to selectable export features
  plugin/src/main/cpp/export/pico_export_plugin.cpp
  plugin/src/main/cpp/include/export/pico_export_plugin.h
Labels: bug, enhancement

#223 Remove deprecated "Contexual" boundary mode on Meta Quest
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/include/export/meta_export_plugin.h
Labels: bug
