Repository GodotVR/godot_openxr_vendors, pull requests merged in 2024-04, with the labels that each got.

#114 Fix project cmake configuration
  common/common.cmake
  godotopenxrkhronos/CMakeLists.txt
  godotopenxrlynx/CMakeLists.txt
  godotopenxrmeta/CMakeLists.txt
  godotopenxrpico/CMakeLists.txt
Labels: bug, enhancement

#118 [2.x] Code cleanup for the export logic
  CHANGES.md
  godotopenxrkhronos/src/main/cpp/export/khronos_export_plugin.cpp
  godotopenxrkhronos/src/main/cpp/export/khronos_export_plugin.h
  godotopenxrlynx/src/main/cpp/export/lynx_export_plugin.cpp
  godotopenxrlynx/src/main/cpp/export/lynx_export_plugin.h
  godotopenxrmeta/src/main/cpp/export/meta_export_plugin.cpp
  godotopenxrmeta/src/main/cpp/export/meta_export_plugin.h
  godotopenxrpico/src/main/cpp/export/pico_export_plugin.cpp
  godotopenxrpico/src/main/cpp/export/pico_export_plugin.h
Labels: bug, cherry-pick

#120 Add missing changelog entry about API for scene anchors
  CHANGES.md
Labels: bug

#124 Simplify the plugin's build process
  README.md
  build.gradle
  godotopenxrkhronos/build.gradle
  godotopenxrlynx/build.gradle
  godotopenxrmeta/build.gradle
  godotopenxrpico/build.gradle
Labels: enhancement

#116 Add XR_FB_hand_tracking_capsules extension wrapper
  CHANGES.md
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_capsules_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_fb_hand_tracking_capsules_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
Labels: enhancement

#115 Implement remaining functionality in XR_FB_passthrough extension wrapper
  CHANGES.md
  common/src/main/cpp/classes/openxr_fb_passthrough_geometry.cpp
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  common/src/main/cpp/include/classes/openxr_fb_passthrough_geometry.h
  common/src/main/cpp/include/extensions/openxr_fb_passthrough_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
  demo/main.gd
  demo/main.tscn
Labels: enhancement

#119 Implement XR_META_passthrough_preferences extension
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_fb_passthrough_extension_wrapper.h
Labels: enhancement

#123 Implement XR_META_passthrough_color_lut extension
  CHANGES.md
  common/src/main/cpp/classes/openxr_meta_passthrough_color_lut.cpp
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  common/src/main/cpp/include/classes/openxr_meta_passthrough_color_lut.h
  common/src/main/cpp/include/extensions/openxr_fb_passthrough_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
  demo/assets/color-lut-inverted-32.png
  demo/assets/color-lut-inverted-32.png.import
  demo/assets/color-lut.png
  demo/assets/color-lut.png.import
  demo/main.gd
  demo/main.tscn
Labels: enhancement

#132 Fix crash caused by missing `return`
  common/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
Labels: bug

#134 Fix `XRBodyModifier3D` moved to wrong place in demo after rebase
  demo/main.tscn
Labels: bug
