Repository GodotVR/godot_openxr_vendors, pull requests merged in 2024-03, with the labels that each got.

#98 Add XR_FB_hand_tracking_mesh extension wrapper and OpenXRFbHandTrackingMesh node
  CHANGES.md
  common/src/main/cpp/classes/openxr_fb_hand_tracking_mesh.cpp
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_mesh_extension_wrapper.cpp
  common/src/main/cpp/include/classes/openxr_fb_hand_tracking_mesh.h
  common/src/main/cpp/include/extensions/openxr_fb_hand_tracking_mesh_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
  demo/main.gd
  demo/main.tscn
Labels: enhancement

#100 Initialize all values of XrHandTrackingScaleFB struct
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_mesh_extension_wrapper.cpp
Labels: bug

#81 Implement XR_FB_hand_tracking_aim extension
  CHANGES.md
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_aim_extension_wrapper.cpp
  common/src/main/cpp/include/extensions/openxr_fb_hand_tracking_aim_extension_wrapper.h
  common/src/main/cpp/register_types.cpp
  demo/main.gd
  demo/main.tscn
  demo/project.godot
  demo/xr_fb_hand_tracking_aim_demo.gd
  demo/xr_fb_hand_tracking_aim_demo.tscn
Labels: enhancement

#102 Fix issue with only the first permission being requested
  godotopenxrmeta/src/main/java/org/godotengine/openxr/vendors/meta/GodotOpenXRMeta.kt
Labels: bug

#103 [2.x] Fix issue with only the first permission being requested
  CHANGES.md
  godotopenxrmeta/src/main/java/org/godotengine/openxr/vendors/meta/GodotOpenXRMeta.kt
Labels: bug, cherry-pick

#104 [2.x] Added Malcolm, David and Logan as contributors.
  CONTRIBUTORS.md
Labels: enhancement, cherry-pick

#105 Make XR_FB_hand_tracking_aim project setting basic
  common/src/main/cpp/extensions/openxr_fb_hand_tracking_aim_extension_wrapper.cpp
Labels: enhancement

#106 Add .gitignore for asset to prevent checking in temp dlls
  demo/addons/godotopenxrvendors/.gitignore
Labels: enhancement

#108 Fix hand tracking mesh skeleton setup
  common/src/main/cpp/classes/openxr_fb_hand_tracking_mesh.cpp
Labels: bug
