Repository GodotVR/godot_openxr_vendors, pull requests merged in 2024-07, with the labels that each got.

#184 Move the OpenXR version to the common `config.gradle`
  config.gradle
  godotopenxrkhronos/build.gradle
  godotopenxrpico/build.gradle
Labels: enhancement

#177 Create Meta Passthrough tutorial doc
  CHANGES.md
  docs/manual/meta/img/passthrough/bcs_passthrough_filter.jpg
  docs/manual/meta/img/passthrough/color_lut_passthrough_filter.jpg
  docs/manual/meta/img/passthrough/color_map_passthrough_filter.jpg
  docs/manual/meta/img/passthrough/edge_color_passthrough_filter.jpg
  docs/manual/meta/img/passthrough/mono_map_passthrough_filter.jpg
  docs/manual/meta/img/passthrough/node_tree_passthrough_geometry.png
  docs/manual/meta/img/passthrough/passthrough_color_lut_resource.png
  docs/manual/meta/img/passthrough/passthrough_color_map_resource.png
  docs/manual/meta/img/passthrough/passthrough_export_settings.png
  docs/manual/meta/img/passthrough/passthrough_mono_map_resource.png
  docs/manual/meta/img/passthrough/projected_passthrough.jpg
  docs/manual/meta/img/passthrough/projected_passthrough_hole_punch.jpg
  docs/manual/meta/img/passthrough/reconstruction_passthrough.jpg
  docs/manual/meta/img/scene_manager/export_settings.png
  docs/manual/meta/img/scene_manager/global_mesh.png
  docs/manual/meta/img/scene_manager/global_mesh_wireframe.png
  docs/manual/meta/img/scene_manager/scene_manager_options.png
  docs/manual/meta/img/scene_manager/scene_tree.png
  docs/manual/meta/img/scene_manager/spatial_entities.png
  docs/manual/meta/img/scene_manager/spatial_entity_scene.png
  docs/manual/meta/index.rst
  docs/manual/meta/passthrough.rst
  docs/manual/meta/scene_manager.rst
Labels: documentation

#181 Add support for overriding non-selected Khronos vendor options
  common/src/main/cpp/export/khronos_export_plugin.cpp
  common/src/main/cpp/export/meta_export_plugin.cpp
  common/src/main/cpp/export/pico_export_plugin.cpp
  common/src/main/cpp/include/export/khronos_export_plugin.h
Labels: enhancement, discussion

#189 Use SCons and Gradle cache on CI to improve build times
  .github/workflows/build-addon-on-push.yml
Labels: enhancement

#186 Add Meta Composition Layer tutorial doc
  docs/manual/meta/composition_layers.rst
  docs/manual/meta/img/composition_layers/alpha_blend_example.png
  docs/manual/meta/img/composition_layers/alpha_blend_properties.png
  docs/manual/meta/img/composition_layers/filter_settings_properties.png
  docs/manual/meta/img/composition_layers/secure_content_example.png
  docs/manual/meta/img/composition_layers/secure_content_properties.png
  docs/manual/meta/index.rst
Labels: documentation

#187 Create Meta Hand Tracking tutorial doc
  docs/manual/meta/hand_tracking.rst
  docs/manual/meta/img/hand_tracking/hand_aim_project_setting.png
  docs/manual/meta/img/hand_tracking/hand_aim_tracker_property.png
  docs/manual/meta/img/hand_tracking/hand_capsules_collision_shape.png
  docs/manual/meta/img/hand_tracking/hand_capsules_mesh.png
  docs/manual/meta/img/hand_tracking/hand_mesh.png
  docs/manual/meta/img/hand_tracking/hand_mesh_material.png
  docs/manual/meta/img/hand_tracking/hand_mesh_node_tree.png
  docs/manual/meta/img/hand_tracking/hand_tracking_export_setting.png
  docs/manual/meta/img/hand_tracking/hand_tracking_project_setting.png
  docs/manual/meta/img/hand_tracking/menu_system_gestures.png
  docs/manual/meta/index.rst
Labels: documentation

#188 Create Meta Spatial Anchor tutorial doc
  docs/manual/meta/img/spatial_anchors/colored_cylinders.png
  docs/manual/meta/img/spatial_anchors/cylinders.png
  docs/manual/meta/img/spatial_anchors/spatial_anchor_export_setting.png
  docs/manual/meta/img/spatial_anchors/spatial_anchor_manager_node.png
  docs/manual/meta/img/spatial_anchors/spatial_anchor_scene.png
  docs/manual/meta/index.rst
  docs/manual/meta/scene_manager.rst
  docs/manual/meta/spatial_anchors.rst
Labels: documentation

#191 Add readme files and screenshots to sample projects
  samples/meta-body-tracking-sample/README.md
  samples/meta-body-tracking-sample/screenshots/meta_body_tracking_screenshot_01.png
  samples/meta-composition-layers-sample/README.md
  samples/meta-composition-layers-sample/screenshots/meta_comp_layers_screenshot_01.png
  samples/meta-composition-layers-sample/screenshots/meta_comp_layers_screenshot_02.png
  samples/meta-hand-tracking-sample/README.md
  samples/meta-hand-tracking-sample/screenshots/meta_hand_tracking_screenshot_01.png
  samples/meta-passthrough-sample/README.md
  samples/meta-passthrough-sample/screenshots/meta_passthrough_screenshot_01.png
  samples/meta-passthrough-sample/screenshots/meta_passthrough_screenshot_02.png
  samples/meta-scene-sample/README.md
  samples/meta-scene-sample/screenshots/meta_sceen_screenshot_01.png
Labels: documentation

#194 Meta Quest: Show the splash screen in passthrough if environment blend mode isn't opaque
  common/src/main/cpp/export/meta_export_plugin.cpp
Labels: enhancement

#195 Update scene_manager.rst
  docs/manual/meta/scene_manager.rst
Labels: documentation
