Repository GodotVR/godot_openxr_vendors, pull requests merged in 2025-01, with the labels that each got.

#241 Fix wall, floor and ceiling collision shapes with Jolt physics
  plugin/src/main/cpp/classes/openxr_fb_spatial_entity.cpp
  plugin/src/main/cpp/register_types.cpp
Labels: bug

#231 Only add the `LAUNCHER` category if "Show in App Library" is enabled
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/cpp/export/khronos_export_plugin.cpp
  plugin/src/main/cpp/export/magicleap_export_plugin.cpp
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/include/export/magicleap_export_plugin.h
Labels: enhancement

#247 Remove stray double quote from `AndroidManifest.xml`
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/cpp/export/meta_export_plugin.cpp
Labels: bug

#248 Update GitHub Actions to create a "draft" release, so publishing triggers MavenCentral Publish
  .github/workflows/build-addon-on-push.yml
Labels: bug

#208 Add support for `XR_FB_android_surface_swapchain_create`
  plugin/src/main/common.cmake
  plugin/src/main/cpp/extensions/openxr_fb_android_surface_swapchain_create_extension_wrapper.cpp
  plugin/src/main/cpp/include/extensions/openxr_fb_android_surface_swapchain_create_extension_wrapper.h
  plugin/src/main/cpp/register_types.cpp
  samples/meta-passthrough-sample/main.tscn
Labels: enhancement

#245 Support making hybrid apps for Meta headsets
  config.gradle
  plugin/build.gradle
  plugin/src/main/cpp/classes/openxr_hybrid_app.cpp
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/cpp/export/khronos_export_plugin.cpp
  plugin/src/main/cpp/export/magicleap_export_plugin.cpp
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/include/classes/openxr_hybrid_app.h
  plugin/src/main/cpp/include/export/export_plugin.h
  plugin/src/main/cpp/register_types.cpp
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotOpenXRHybridAppInternal.kt
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotPanelApp.kt
  plugin/src/main/res/values/themes.xml
  plugin/src/meta/AndroidManifest.xml
  samples/hybrid-app-sample/.gitattributes
  samples/hybrid-app-sample/.gitignore
  samples/hybrid-app-sample/assets/gltf/turkey.glb
  samples/hybrid-app-sample/assets/gltf/turkey.glb.import
  samples/hybrid-app-sample/export_presets.cfg
  samples/hybrid-app-sample/icon.svg
  samples/hybrid-app-sample/icon.svg.import
  samples/hybrid-app-sample/main.gd
  samples/hybrid-app-sample/main.gd.uid
  samples/hybrid-app-sample/main.tscn
  samples/hybrid-app-sample/openxr_action_map.tres
  samples/hybrid-app-sample/panel_switcher.gd
  samples/hybrid-app-sample/panel_switcher.gd.uid
  samples/hybrid-app-sample/panel_switcher.tscn
  samples/hybrid-app-sample/panel_switcher_layer.gd
  samples/hybrid-app-sample/panel_switcher_layer.gd.uid
  samples/hybrid-app-sample/panel_switcher_layer.tscn
  samples/hybrid-app-sample/project.godot
  samples/hybrid-app-sample/start_xr.gd
  samples/hybrid-app-sample/start_xr.gd.uid
  thirdparty/godot_cpp_build_profile/build_profile.json
Labels: enhancement

#226 Implement XR_META_recommended_layer_resolution extension
  plugin/src/main/cpp/extensions/openxr_meta_recommended_layer_resolution_extension_wrapper.cpp
  plugin/src/main/cpp/include/extensions/openxr_meta_recommended_layer_resolution_extension_wrapper.h
  plugin/src/main/cpp/register_types.cpp
Labels: enhancement

#251 Fix the MavenCentral Publish workflow
  .github/workflows/mavencentral-publish.yml
Labels: bug, cherry-pick

#255 Implement instant splash screen for Meta devices
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/include/export/meta_export_plugin.h
Labels: enhancement

#253 Cherry-picks for the godot_openxr_vendors 3.x branch - 1st batch
  .github/workflows/mavencentral-publish.yml
  samples/meta-passthrough-sample/main.gd
Labels: bug
