Repository GodotVR/godot_openxr_vendors, pull requests merged in 2025-04, with the labels that each got.

#272 Use project settings avoid enabling unneeded OpenXR extensions
  .github/workflows/build-addon-on-push.yml
  demo/export_presets.cfg
  demo/project.godot
  plugin/src/main/cpp/classes/openxr_fb_hand_tracking_mesh.cpp
  plugin/src/main/cpp/classes/openxr_fb_render_model.cpp
  plugin/src/main/cpp/classes/openxr_fb_spatial_entity.cpp
  plugin/src/main/cpp/export/khronos_export_plugin.cpp
  plugin/src/main/cpp/export/magicleap_export_plugin.cpp
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/export/pico_export_plugin.cpp
  plugin/src/main/cpp/extensions/openxr_fb_hand_tracking_aim_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_fb_hand_tracking_capsules_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_fb_hand_tracking_mesh_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_meta_recommended_layer_resolution_extension_wrapper.cpp
  plugin/src/main/cpp/include/classes/openxr_fb_hand_tracking_mesh.h
  plugin/src/main/cpp/include/classes/openxr_fb_render_model.h
  plugin/src/main/cpp/include/export/khronos_export_plugin.h
  plugin/src/main/cpp/include/export/magicleap_export_plugin.h
  plugin/src/main/cpp/include/export/meta_export_plugin.h
  plugin/src/main/cpp/include/export/pico_export_plugin.h
  plugin/src/main/cpp/include/extensions/openxr_fb_hand_tracking_aim_extension_wrapper.h
  plugin/src/main/cpp/include/extensions/openxr_fb_hand_tracking_capsules_extension_wrapper.h
  plugin/src/main/cpp/include/extensions/openxr_fb_hand_tracking_mesh_extension_wrapper.h
  plugin/src/main/cpp/include/extensions/openxr_meta_recommended_layer_resolution_extension_wrapper.h
  plugin/src/main/cpp/register_types.cpp
  samples/hybrid-app-sample/export_presets.cfg
  samples/hybrid-app-sample/project.godot
  samples/meta-body-tracking-sample/export_presets.cfg
  samples/meta-body-tracking-sample/project.godot
  samples/meta-composition-layers-sample/export_presets.cfg
  samples/meta-composition-layers-sample/project.godot
  samples/meta-hand-tracking-sample/export_presets.cfg
  samples/meta-hand-tracking-sample/project.godot
  samples/meta-passthrough-sample/export_presets.cfg
  samples/meta-passthrough-sample/project.godot
  samples/meta-scene-sample/export_presets.cfg
  samples/meta-scene-sample/project.godot
Labels: enhancement

#284 Fix standard manifest entries
  plugin/src/khronos/AndroidManifest.xml
Labels: enhancement

#275 Passthrough extensions should override real alpha blend mode, if enabled
  plugin/src/main/cpp/extensions/openxr_fb_passthrough_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_htc_passthrough_extension_wrapper.cpp
Labels: bug

#293 Update CI to use Ubuntu 22.04
  .github/workflows/build-addon-on-push.yml
  .github/workflows/mavencentral-publish.yml
Labels: cherry-pick

#294 Update the main manifest with the latest from the Khronos OpenXR loader
  config.gradle
  plugin/src/khronos/AndroidManifest.xml
  plugin/src/lynx/AndroidManifest.xml
  plugin/src/magicleap/AndroidManifest.xml
  plugin/src/main/AndroidManifest.xml
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotOpenXRHybridAppInternal.kt
  plugin/src/meta/AndroidManifest.xml
  plugin/src/pico/AndroidManifest.xml
Labels: enhancement

#291 Improve hand tracking related code in demo project
  demo/hand_controller.gd
  demo/hand_controller.gd.uid
  demo/hand_mesh.gd
  demo/hand_mesh.gd.uid
  demo/main.gd
  demo/main.tscn
Labels: enhancement

#297 Update docs for meta dynamic resolution
  docs/manual/meta/dynamic_resolution.rst
  docs/manual/meta/img/dynamic_resolution/dynamic_resolution_project_setting.png
  docs/manual/meta/img/recommended_layer_resolution/recommended_layer_resolution_project_setting.png
  docs/manual/meta/index.rst
  docs/manual/meta/recommended_layer_resolution.rst
Labels: documentation

#298 Fix composition layer next chains
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_alpha_blend_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_depth_test_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_image_layout_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_secure_content_extension_wrapper.cpp
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_settings_extension_wrapper.cpp
Labels: bug, cherry-pick

#299 Update `compatibility_minimum` to 4.4
  demo/addons/godotopenxrvendors/plugin.gdextension
Labels: bug

#300 Update docs to reflect project settings changes
  doc_classes/OpenXRFbPassthroughExtensionWrapper.xml
  doc_classes/OpenXRFbSpatialEntityStorageExtensionWrapper.xml
  docs/manual/hybrid_apps.rst
  docs/manual/img/hybrid_apps/hybrid_apps_project_setting.png
  docs/manual/meta/composition_layers.rst
  docs/manual/meta/dynamic_resolution.rst
  docs/manual/meta/hand_tracking.rst
  docs/manual/meta/img/composition_layers/filter_settings_project_setting.png
  docs/manual/meta/img/hand_tracking/hand_tracking_export_setting.png
  docs/manual/meta/img/hand_tracking/hand_tracking_extensions_project_settings.png
  docs/manual/meta/img/hand_tracking/hand_tracking_project_setting.png
  docs/manual/meta/img/passthrough/passthrough_export_settings.png
  docs/manual/meta/img/passthrough/passthrough_project_setting.png
  docs/manual/meta/img/scene_manager/export_settings.png
  docs/manual/meta/img/scene_manager/scene_api_project_setting.png
  docs/manual/meta/img/spatial_anchors/anchor_api_project_setting.png
  docs/manual/meta/img/spatial_anchors/spatial_anchor_export_setting.png
  docs/manual/meta/passthrough.rst
  docs/manual/meta/scene_manager.rst
  docs/manual/meta/spatial_anchors.rst
Labels: documentation
