Repository GodotVR/godot_openxr_vendors, pull requests merged in 2025-02, with the labels that each got.

#254 Misc cleanup
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/export/pico_export_plugin.cpp
  plugin/src/main/cpp/include/export/export_plugin.h
  plugin/src/main/cpp/include/export/meta_export_plugin.h
  plugin/src/main/cpp/include/export/pico_export_plugin.h
Labels: enhancement

#262 Fix the issue preventing overridden vendor options from being updated
  plugin/src/main/cpp/export/export_plugin.cpp
Labels: bug

#264 Fix hybrid app support for recent Godot Android library changes
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotOpenXRHybridAppInternal.kt
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotPanelApp.kt
Labels: bug

#265 Clean scons when doing a Gradle clean
  build.gradle
Labels: enhancement

#269 Add `workflow_dispatch` to the "MavenCentral Publish" workflow to allow manually running it
  .github/workflows/mavencentral-publish.yml
Labels: enhancement, cherry-pick

#270 Add missing Pico store manifest
  plugin/src/pico/AndroidManifest.xml
Labels: bug, cherry-pick

#266 Update for Android library changes in Godot 4.4-beta4
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotPanelApp.kt
Labels: bug

#267 Add support for `XR_FB_composition_layer_image_layout`
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_image_layout_extension_wrapper.cpp
  plugin/src/main/cpp/include/extensions/openxr_fb_composition_layer_image_layout_extension_wrapper.h
  plugin/src/main/cpp/register_types.cpp
Labels: enhancement
