Repository GodotVR/godot_openxr_vendors, pull requests merged in 2025-03, with the labels that each got.

#277 Update demo and samples to 4.4
  demo/addons/godotopenxrvendors/plugin.gdextension.uid
  demo/assets/hand_outline.gdshader.uid
  demo/assets/hand_silhouette.gdshader.uid
  demo/assets/hand_silhouette_outline_mat.tres
  demo/main.gd.uid
  demo/main.tscn
  demo/openxr_action_map.tres
  demo/project.godot
  samples/hybrid-app-sample/panel_switcher.tscn
  samples/hybrid-app-sample/panel_switcher_layer.tscn
  samples/hybrid-app-sample/screenshots/.gdignore
  samples/meta-body-tracking-sample/assets/face/Face.gltf.import
  samples/meta-body-tracking-sample/main.tscn
  samples/meta-body-tracking-sample/openxr_action_map.tres
  samples/meta-body-tracking-sample/project.godot
  samples/meta-body-tracking-sample/screenshots/.gdignore
  samples/meta-body-tracking-sample/start_xr.gd.uid
  samples/meta-composition-layers-sample/example_panel.gd.uid
  samples/meta-composition-layers-sample/example_panel.tscn
  samples/meta-composition-layers-sample/main.gd.uid
  samples/meta-composition-layers-sample/main.tscn
  samples/meta-composition-layers-sample/openxr_action_map.tres
  samples/meta-composition-layers-sample/project.godot
  samples/meta-composition-layers-sample/raycast.gd.uid
  samples/meta-composition-layers-sample/screenshots/.gdignore
  samples/meta-composition-layers-sample/start_xr.gd.uid
  samples/meta-hand-tracking-sample/main.gd.uid
  samples/meta-hand-tracking-sample/main.tscn
  samples/meta-hand-tracking-sample/openxr_action_map.tres
  samples/meta-hand-tracking-sample/pinch_strength.gdshader.uid
  samples/meta-hand-tracking-sample/project.godot
  samples/meta-hand-tracking-sample/raycast.gd.uid
  samples/meta-hand-tracking-sample/screenshots/.gdignore
  samples/meta-hand-tracking-sample/start_xr.gd.uid
  samples/meta-passthrough-sample/geometry.gd.uid
  samples/meta-passthrough-sample/main.gd.uid
  samples/meta-passthrough-sample/main.tscn
  samples/meta-passthrough-sample/openxr_action_map.tres
  samples/meta-passthrough-sample/project.godot
  samples/meta-passthrough-sample/raycast.gd.uid
  samples/meta-passthrough-sample/screenshots/.gdignore
  samples/meta-passthrough-sample/slider.gd.uid
  samples/meta-passthrough-sample/slider.tscn
  samples/meta-passthrough-sample/start_xr.gd.uid
  samples/meta-scene-sample/assets/wireframe-material.gdshader.uid
  samples/meta-scene-sample/main.gd.uid
  samples/meta-scene-sample/main.tscn
  samples/meta-scene-sample/openxr_action_map.tres
  samples/meta-scene-sample/project.godot
  samples/meta-scene-sample/scene_anchor.gd.uid
  samples/meta-scene-sample/scene_anchor.tscn
  samples/meta-scene-sample/scene_global_mesh.gd.uid
  samples/meta-scene-sample/scene_global_mesh.tscn
  samples/meta-scene-sample/screenshots/.gdignore
  samples/meta-scene-sample/spatial_anchor.gd.uid
  samples/meta-scene-sample/spatial_anchor.tscn
  samples/meta-scene-sample/start_xr.gd.uid
Labels: enhancement

#280 Update the configuration and launch mechanism for the hybrid app feature
  config.gradle
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/cpp/export/meta_export_plugin.cpp
  plugin/src/main/cpp/include/export/export_plugin.h
  plugin/src/main/cpp/register_types.cpp
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotOpenXRHybridAppInternal.kt
  plugin/src/main/java/org/godotengine/openxr/vendors/GodotPanelApp.kt
  samples/.gitignore
  samples/hybrid-app-sample/export_presets.cfg
  samples/hybrid-app-sample/project.godot
Labels: bug, enhancement

#285 Fix `OpenXRFbSpatialEntityStorageExtensionWrapper` typos
  plugin/src/main/cpp/extensions/openxr_fb_spatial_entity_storage_extension_wrapper.cpp
  plugin/src/main/cpp/include/extensions/openxr_fb_spatial_entity_storage_extension_wrapper.h
  plugin/src/main/cpp/register_types.cpp
Labels: bug, cherry-pick

#287 Switch the theme for `GodotPanelApp` to match the one used by `GodotApp`
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/res/values/themes.xml
Labels: bug, enhancement

#286 Enable depth test for quad layers
  plugin/src/main/cpp/extensions/openxr_fb_composition_layer_depth_test_extension_wrapper.cpp
  plugin/src/main/cpp/include/extensions/openxr_fb_composition_layer_depth_test_extension_wrapper.h
  plugin/src/main/cpp/register_types.cpp
Labels: enhancement
