Repository GodotVR/godot_openxr_vendors, pull requests merged in 2025-07, with the labels that each got.

#318 Configure all samples to use REC709 color space
  demo/project.godot
  samples/hybrid-app-sample/project.godot
  samples/meta-body-tracking-sample/project.godot
  samples/meta-composition-layers-sample/project.godot
  samples/meta-hand-tracking-sample/project.godot
  samples/meta-passthrough-sample/project.godot
  samples/meta-scene-sample/project.godot
  samples/meta-space-warp-sample/project.godot
Labels: enhancement

#320 Update the maven publishing configuration following the deprecation of the OSSHR service
  build.gradle
  config.gradle
  plugin/src/main/cpp/export/export_plugin.cpp
  plugin/src/main/cpp/include/export/export_plugin.h
  scripts/publish-root.gradle
  settings.gradle
Labels: bug

#314 Use the Meta OpenXR preview headers in CI builds
  .github/workflows/build-addon-on-push.yml
  .github/workflows/mavencentral-publish.yml
Labels: enhancement

#324 Add missing 2.0.4 changelog entries
  CHANGES.md
Labels: bug, documentation

#323 Add a debug version of the maven central artifact for the OpenXR Vendors library
  config.gradle
  plugin/build.gradle
  plugin/src/main/cpp/include/export/export_plugin.h
  scripts/publish-module.gradle
Labels: bug, enhancement

#329 Update the export plugin version to match the maven central release
  CHANGES.md
  config.gradle
  plugin/src/main/cpp/include/export/export_plugin.h
Labels: bug

#330 Automatically check version numbers before release
  .github/workflows/build-addon-on-push.yml
  scripts/validate_release.py
Labels: enhancement
